### ISSUE TITLE
Hey I have lot of issues while running both backend and frontend

### ISSUE THREAD

**Issue by vestigialcode** [guido-an/Nextjs-E-Commerce#9]
here is the error log of backend
`Listening on http://localhost:undefined
Connected to Mongo! Database name: "backend"
Error: Missing credentials for "PLAIN"
    at SMTPConnection._formatError (/Users/dibyajiban/Desktop/nextjs/Nextjs-E-Commerce/backend/node_modules/nodemailer/lib/smtp-connection/index.js:781:19)
    at SMTPConnection.login (/Users/dibyajiban/Desktop/nextjs/Nextjs-E-Commerce/backend/node_modules/nodemailer/lib/smtp-connection/index.js:452:38)
    at /Users/dibyajiban/Desktop/nextjs/Nextjs-E-Commerce/backend/node_modules/nodemailer/lib/smtp-transport/index.js:374:32
    at SMTPConnection.<anonymous> (/Users/dibyajiban/Desktop/nextjs/Nextjs-E-Commerce/backend/node_modules/nodemailer/lib/smtp-connection/index.js:209:17)
    at Object.onceWrapper (events.js:421:28)
    at SMTPConnection.emit (events.js:315:20)
    at SMTPConnection._actionEHLO (/Users/dibyajiban/Desktop/nextjs/Nextjs-E-Commerce/backend/node_modules/nodemailer/lib/smtp-connection/index.js:1309:14)
    at SMTPConnection._processResponse (/Users/dibyajiban/Desktop/nextjs/Nextjs-E-Commerce/backend/node_modules/nodemailer/lib/smtp-connection/index.js:940:20)
    at SMTPConnection._onData (/Users/dibyajiban/Desktop/nextjs/Nextjs-E-Commerce/backend/node_modules/nodemailer/lib/smtp-connection/index.js:746:14)
    at TLSSocket.SMTPConnection._onSocketData (/Users/dibyajiban/Desktop/nextjs/Nextjs-E-Commerce/backend/node_modules/nodemailer/lib/smtp-connection/index.js:189:46)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
  code: 'EAUTH',
  command: 'API'
}`

**Comment by vestigialcode** [comment]
**Can you help me out... :)**

**Comment by guido-an** [comment]
Hey vestigialcode,

Sorry but I am reading this only now. 

This is a project built few years ago just for learning purposes.

Anyway, now both frontend and backend should run correctly, just specify the PORT in the .env file (backend)
